# Start windows and panes at index 1, not 0.
set -g base-index 1
setw -g pane-base-index 1

# Enable mouse scrolling.
set -g mouse on

# Styling the status bar.
set -g status-bg "#86626E"
set -g status-fg "#FBF5F3"
set -g status-left "[#S] "
set -g status-right "%a %d %b %H:%M"

# Enable activity monitoring.
setw -g monitor-activity on
set -g visual-activity on

# Highliight the active window.
setw -g window-status-current-style "fg=#06D6A0"

